"use client";

import { ChevronDown, ChevronUp } from "lucide-react";
import { useState } from "react";

export function SeoGuide() {
    const [openSection, setOpenSection] = useState<string | null>("yield");

    const toggle = (id: string) => setOpenSection(openSection === id ? null : id);

    return (
        <div className="w-full max-w-4xl mx-auto mt-20 px-6 pb-20 text-blue-100/80">
            <div className="prose prose-invert max-w-none">
                <h2 className="text-3xl font-bold text-white mb-8 text-center">Real Estate Investment Guide</h2>

                <div className="grid gap-6">
                    <Section
                        title="What is Rental Yield?"
                        isOpen={openSection === "yield"}
                        onClick={() => toggle("yield")}
                    >
                        <p>
                            Rental yield is a key metric for real estate investors that measures the return on investment (ROI) generated by a rental property. It is expressed as a percentage of the property's value.
                            <strong> Gross Yield</strong> looks at total income before expenses, while <strong>Net Yield</strong> accounts for costs like maintenance, taxes, and insurance.
                        </p>
                    </Section>

                    <Section
                        title="How is Cash on Cash Return different?"
                        isOpen={openSection === "cash"}
                        onClick={() => toggle("cash")}
                    >
                        <p>
                            While standard yield metrics look at the property value, <strong>Cash on Cash Return</strong> measures the return on the actual <em>cash</em> you invested.
                            This is critical for investors using a mortgage.
                        </p>
                        <div className="bg-brand-950/50 p-4 rounded-lg my-4 border border-brand-500/20 font-mono text-sm">
                            Formula: (Annual Cash Flow / Total Cash Invested) × 100
                        </div>
                        <p>
                            If you put $50,000 down on a $250,000 property and make $5,000/year in profit, your Cash on Cash return is 10%, which is often much higher than the Cap Rate (Net Yield).
                        </p>
                    </Section>

                    <Section
                        title="Understanding Cap Rate vs. ROI"
                        isOpen={openSection === "cap"}
                        onClick={() => toggle("cap")}
                    >
                        <ul className="list-disc pl-5 space-y-2 mt-2">
                            <li><strong>Cap Rate (Capitalization Rate):</strong> Measures a property's natural potential return without considering debt. It helps compare properties purely on their merit.</li>
                            <li><strong>ROI (Return on Investment):</strong> A broader term that often includes mortgage paydown and appreciation.</li>
                        </ul>
                    </Section>
                </div>
            </div>
        </div>
    );
}

function Section({ title, isOpen, onClick, children }: { title: string, isOpen: boolean, onClick: () => void, children: React.ReactNode }) {
    return (
        <div className="border border-white/10 rounded-xl overflow-hidden bg-white/5 backdrop-blur-sm transition-all duration-300">
            <button
                onClick={onClick}
                className="flex items-center justify-between w-full p-6 text-left hover:bg-white/5 transition-colors"
            >
                <span className="text-xl font-semibold text-white">{title}</span>
                {isOpen ? <ChevronUp className="text-brand-400" /> : <ChevronDown className="text-gray-500" />}
            </button>
            {isOpen && (
                <div className="p-6 pt-0 text-lg leading-relaxed border-t border-white/5 animate-in slide-in-from-top-2 duration-200">
                    {children}
                </div>
            )}
        </div>
    );
}
